### PR TITLE
Add parthea as maintainer

### PR DESCRIPTION
**Pull request by parthea**
Hello,

I'd like to request to be added as a maintainer for this repo.

### CODE REVIEW

**Comment by parthea** [comment]
cc @johanneskoester

**Comment by parthea** [comment]
@ocefpaf  - Could I be added as a maintainer for this repo? I am already a maintainer for the following repos: 

https://github.com/conda-forge/google-cloud-bigquery-feedstock
https://github.com/conda-forge/google-cloud-core-feedstock

`google-cloud-bigquery` depends on `google-resumable-media` so being a maintainer for both will allow me to publish `google-cloud-bigquery` updates quickly.

**Comment by ocefpaf** [comment]
Ping @johanneskoester who is the maintainer here.

**Comment by johanneskoester** [comment]
Sorry for the delay!

**Comment by parthea** [comment]
Thanks @johanneskoester!

**Pull request merged**
